### PR TITLE
Update LogicBuilder.Expressions.Utils

### LINKED ISSUE #186: Update dependency LogicBuilder.Expressions.Utils
## The issue
This library relies on `LogicBuilder.Expressions.Utils v5.0.6` which relies on `System.Linq.Dynamic.Core v1.2.14`.

## Why is this an issue?
`System.Linq.Dynamic.Core` contains a severe vulnerability in version `1.2.14`.

## What is LogicBuilder.Expressions.Utils doing about it?
They updated the dependency to a safer version as seen in [this commit](https://github.com/BlaiseD/LogicBuilder.DataComponents/commit/bf2ba0447c6b9afa46cc72aeb40e3961edefee77). 

## What can do?
We should update `LogicBuilder.Expressions.Utils` to `5.0.10` (fixed in 5.0.9, but better to get latest patch) to get the fix.

### PR DESCRIPTION
**Pull request by matthewtquinn1**
Resolves #186

### CODE REVIEW

**Comment by matthewtquinn1** [comment]
@BlaiseD OK to merge? 😄

**Comment by BlaiseD** [comment]
@matthewtquinn1 -  we should be all set once you sign the CLA.

**Comment by matthewtquinn1** [comment]
@BlaiseD Thank you. 

had a look at the CLA - it says the author must sign it; would that be the author of the repo? Or this PR?

**Comment by BlaiseD** [comment]
> @BlaiseD Thank you.
> 
> had a look at the CLA - it says the author must sign it; would that be the author of the repo? Or this PR?

Must be the PR.  The CLA check only come up on your first contribution.

**Comment by matthewtquinn1** [comment]
Sorry I've never seen this before. Is there a guide for how to sign it?

**Comment by matthewtquinn1** [comment]
@microsoft-github-policy-service agree

**Comment by BlaiseD** [comment]
[This](https://adrientorris.github.io/github/how-to-sign-microsoft-cla-on-github.html) might help.  Here's [another resource](https://github.com/microsoft/contributorlicenseagreement).

**Comment by matthewtquinn1** [comment]
@BlaiseD That first link no longer works, they say that it is an old and unused method of doing it now ;( 

The second link, I see it suggests how to accept it here but I followed that step and it still hasn't passed https://[cla2.dotnetfoundation.org](https://cla2.dotnetfoundation.org/)/

**Comment by BlaiseD** [comment]
Here's an [example](https://github.com/AutoMapper/AutoMapper.Extensions.ExpressionMapping/pull/171) from another PR.

**Comment by matthewtquinn1** [comment]
@dotnet-policy-service agree company="Full Staq Ltd"

**Comment by matthewtquinn1** [comment]
@BlaiseD Got it! Ready to merge :)

**Comment by BlaiseD** [comment]
@jbogard - is it possible part of the CLA workflow is missing for [AutoMapper.Extensions.OData](https://github.com/AutoMapper/AutoMapper.Extensions.OData)?  I suspect the prompt/instructions were not clear/visible for @matthewtquinn1 compared with e.g. this [PR](https://github.com/AutoMapper/AutoMapper.Extensions.ExpressionMapping/pull/171) from the Expression Mapping repo.

**Pull request merged**
