### PR TITLE
pass QuerySettings in GetAsync/Get/GetQuery

### LINKED ISSUE #62: Support for ODataQuerySettings in GetAsync/Get
Hello Blaise,

I have noticed that the `GetAsync` and `Get` method contains a `handleNullPropagation` argument, that is later used to create the `ODataQuerySettings ` in the `LinqExtensions.ToFilterExpression` method. 

However, to configure other options like the PageSize, I think it is better to allow the ODataQuerySettings to be passed directly in both Get methods. 

Something similar was also requested in issue #43 .

I have added a working inplementation here, if you agree I can send you a PR.

Branch:
https://github.com/fw2568/AutoMapper.Extensions.OData/tree/querysettings

Compare with current master:
https://github.com/AutoMapper/AutoMapper.Extensions.OData/compare/master...fw2568:querysettings 

Best Regards,
Frank

### PR DESCRIPTION
**Pull request by fw2568**
As discussed in issue #62 , this PRs intend was to allow the ODataQuerySettings to be passed in the methods IQueryable.Get/GetAsync/GetQuery.

However later we came to the conclusion that it would be better to use our own query settings type (QuerySettings) as not all options of ODataQuerySettings are supported currently. 

closes #62

### CODE REVIEW

**Comment by fw2568** [comment]
just have seen that I still have to add the tests.

**Comment by BlaiseD** [comment]
@fw2568 - I see another concern here.  The change isn't solving a problem.  Plus it indicates that `ODataQuerySettings` is being supported without providing implementations i.e. it invites questions like "Why isn't `ODataQuerySettings.PageSize` being applied?"

Is there a functional problem you were trying to solve?

**Comment by fw2568** [comment]
I see what you mean. I just have added a test to see if page size is applied, but it isn't. Actually I have assumed that this is handled within the OData Core library. 

The reason why I asking this, is that we have to use the nextlink feature with skip token that is provided only when you restrict the response in the server side with the PageSize property. 
see also: https://devblogs.microsoft.com/odata/using-skiptoken-for-paging-in-asp-net-odata-and-asp-net-core-odata/

But I understand that not all of the features support by ODataQuerySettings are currently implemented here. Maybe a good step in between would be to use a custom type "`AutomapperODataQuerySettings`" (only an example), 

This would allow to keep the API stable (as it would only contain the HandleNullPropagation currently) without misleading that a option is not considered currently. 

To add PageSize support I would have to get deeper into your implementation, but I could try to add this with another PR.

**Comment by BlaiseD** [comment]
Correct.  Just about every feature involves creating our own expressions.  Even e.g. the `ToFilterExpression` implementation could be replaced with [our own](https://github.com/AutoMapper/AutoMapper.Extensions.OData/blob/cbcb9fd9b11878d14db25c2a13d0d59f6705d36f/AutoMapper.AspNetCore.OData.EFCore/Visitors/FilterAppender.cs#L34) which we needed for filtering child collections.  No reason to replace it at the top level while it still works.

Maybe just `QuerySettings` as a name for the custom class?  And we won't need the PageSize test until you're ready - assuming `HandleNullPropagation` will be the only property initially.

Thanks.

**Comment by fw2568** [comment]
Ok. Then I will update the code to use a new class QuerySettings instead of ODataQuerySettings and will remove the useless test.

**Comment by fw2568** [comment]
@BlaiseD changes are complete again, please review.

**Comment by mariolopezmartinez** [comment]
Howdy hey, thank you both for your hard work on solving this issue. Is there an ETA on when this will make it to the next release for the package?

**Comment by BlaiseD** [comment]
This merge is part of the [latest preview](https://www.nuget.org/packages/AutoMapper.AspNetCore.OData.EFCore/2.0.3-preview.0).

It adds no additional features though - not sure what you're looking for - PRs  are welcome.

**Comment by mariolopezmartinez** [comment]
The issue I was facing was the lack of way to set a default PageSize with the lack of the [EnableQuery] annotation.

And I now see I was mistaken when reading what was included in this PR, since the PageSize attribute was left out of the QuerySettings class.

I can take a look at the initial PR after work today and look for those improvements. In the meanwhile, is there any sort of workaround you would recommend?

**Comment by BlaiseD** [comment]
Yep the PR will have to be clear on when the new parameters (PageNumber, PageSize etc..) take precedence over the query options.

The [tests](https://github.com/AutoMapper/AutoMapper.Extensions.OData/blob/2fcb6695640e1710f87f3ac427bdeac045e8f747/ExpressionBuilder.Tests/ODataHelpers.cs#L86) may give ideas about creating `ODataQueryOpions` on the server but then you'll need to reconcile that with the request.

You know as much as I do.  StackOverflow?

**Pull request merged**
